from typing import Protocol

from schemas.campaign import CampaignDetail, CampaignRecord
from schemas.company import Company, CompanyCreate
from schemas.dashboard import DashboardData
from schemas.email import EmailDraft, EmailWorkspaceData
from schemas.intelligence import CompanyIntelligence, IntelligenceRunRecord


class Store(Protocol):
    def create_company(self, data: CompanyCreate) -> Company: ...
    def get_company(self, company_id: str) -> Company | None: ...
    def list_companies(self) -> list[Company]: ...

    def save_intelligence(
        self, company_id: str, intelligence: CompanyIntelligence
    ) -> IntelligenceRunRecord: ...
    def get_intelligence_by_company(self, company_id: str) -> IntelligenceRunRecord | None: ...
    def get_intelligence_run(self, run_id: str) -> IntelligenceRunRecord | None: ...

    def create_campaign(
        self,
        company_id: str,
        intelligence_run_id: str,
        name: str,
        opportunity_score: int,
    ) -> CampaignRecord: ...
    def get_campaign(self, campaign_id: str) -> CampaignRecord | None: ...
    def list_campaigns(self) -> list[CampaignRecord]: ...
    def get_campaign_detail(self, campaign_id: str) -> CampaignDetail | None: ...
    def update_campaign_status(self, campaign_id: str, status: str) -> CampaignRecord | None: ...

    def save_emails(self, campaign_id: str, emails: list[EmailDraft]) -> list[EmailDraft]: ...
    def get_emails_for_campaign(self, campaign_id: str) -> list[EmailDraft]: ...
    def get_email(self, email_id: str) -> EmailDraft | None: ...
    def update_email(self, email_id: str, **fields) -> EmailDraft | None: ...
    def get_email_workspace(self, campaign_id: str) -> EmailWorkspaceData | None: ...

    def add_activity(self, message: str) -> None: ...
    def get_dashboard(self) -> DashboardData: ...

    def save_source_documents(self, company_id: str, documents: list[dict]) -> None: ...
