import type { Contact } from "@/lib/types";

const HOUR = 60 * 60 * 1000;
const DAY = 24 * HOUR;
const iso = (offsetMs: number) =>
  new Date(Date.now() - offsetMs).toISOString();

export function getMockContacts(): Contact[] {
  return [
    {
      id: "c1",
      first_name: "Layla",
      last_name: "Al-Mansoori",
      title: "Head of AI",
      seniority: "Director",
      email: "layla.almansoori@core42.ai",
      company_id: "core42",
      company_name: "Core42",
      industry: "AI Infrastructure",
      status: "Contacted",
      tags: ["AI Strategy", "Decision Maker"],
      added_at: iso(8 * DAY),
      last_activity_at: iso(2 * HOUR),
      last_activity: "Opened Email 1",
    },
    {
      id: "c2",
      first_name: "Omar",
      last_name: "Hassan",
      title: "Head of Cloud",
      seniority: "Director",
      email: "omar.hassan@core42.ai",
      company_id: "core42",
      company_name: "Core42",
      industry: "AI Infrastructure",
      status: "Replied",
      tags: ["Cloud", "Champion"],
      added_at: iso(8 * DAY),
      last_activity_at: iso(5 * HOUR),
      last_activity: "Replied to Email 1",
    },
    {
      id: "c3",
      first_name: "Aisha",
      last_name: "Khan",
      title: "VP Engineering",
      seniority: "VP",
      email: "aisha.khan@core42.ai",
      company_id: "core42",
      company_name: "Core42",
      industry: "AI Infrastructure",
      status: "Queued",
      tags: ["Engineering"],
      added_at: iso(6 * DAY),
    },
    {
      id: "c4",
      first_name: "Yusuf",
      last_name: "Ibrahim",
      title: "Chief Data Officer",
      seniority: "C-Level",
      email: "yusuf.ibrahim@presight.ai",
      company_id: "presight",
      company_name: "Presight AI",
      industry: "AI Analytics",
      status: "Contacted",
      tags: ["Data", "Decision Maker"],
      added_at: iso(11 * DAY),
      last_activity_at: iso(1 * DAY),
      last_activity: "Email 1 sent",
    },
    {
      id: "c5",
      first_name: "Mariam",
      last_name: "El-Sayed",
      title: "Director of AI Governance",
      seniority: "Director",
      email: "mariam.elsayed@presight.ai",
      company_id: "presight",
      company_name: "Presight AI",
      industry: "AI Analytics",
      status: "Not Contacted",
      tags: ["Governance", "Compliance"],
      added_at: iso(3 * DAY),
    },
    {
      id: "c6",
      first_name: "Dr. Karim",
      last_name: "Saleh",
      title: "Head of Clinical AI",
      seniority: "Director",
      email: "karim.saleh@g42healthcare.ai",
      company_id: "g42-healthcare",
      company_name: "G42 Healthcare",
      industry: "Healthcare AI",
      status: "Contacted",
      tags: ["Healthcare", "Decision Maker"],
      added_at: iso(14 * DAY),
      last_activity_at: iso(2 * DAY),
      last_activity: "Email 2 sent",
    },
    {
      id: "c7",
      first_name: "Noura",
      last_name: "Al-Mazrouei",
      title: "CISO",
      seniority: "C-Level",
      email: "noura.almazrouei@g42healthcare.ai",
      company_id: "g42-healthcare",
      company_name: "G42 Healthcare",
      industry: "Healthcare AI",
      status: "Replied",
      tags: ["Security", "Champion"],
      added_at: iso(20 * DAY),
      last_activity_at: iso(9 * HOUR),
      last_activity: "Replied — wants demo",
    },
    {
      id: "c8",
      first_name: "Faisal",
      last_name: "Al-Rashid",
      title: "Head of Geospatial Intelligence",
      seniority: "Director",
      email: "faisal.alrashid@bayanat.ae",
      company_id: "bayanat",
      company_name: "Bayanat",
      industry: "Geospatial AI",
      status: "Queued",
      tags: ["Geospatial"],
      added_at: iso(5 * DAY),
    },
    {
      id: "c9",
      first_name: "Hessa",
      last_name: "Al-Suwaidi",
      title: "VP Strategy",
      seniority: "VP",
      email: "hessa.alsuwaidi@bayanat.ae",
      company_id: "bayanat",
      company_name: "Bayanat",
      industry: "Geospatial AI",
      status: "Not Contacted",
      tags: ["Strategy"],
      added_at: iso(2 * DAY),
    },
    {
      id: "c10",
      first_name: "Dr. Mahmoud",
      last_name: "Khalifa",
      title: "Head of Research",
      seniority: "Director",
      email: "mahmoud.khalifa@tii.ae",
      company_id: "tii",
      company_name: "Technology Innovation Institute",
      industry: "AI Research",
      status: "Contacted",
      tags: ["Research"],
      added_at: iso(17 * DAY),
      last_activity_at: iso(3 * DAY),
      last_activity: "Email 1 sent",
    },
    {
      id: "c11",
      first_name: "Salma",
      last_name: "Rahimi",
      title: "AI Platform Engineer",
      seniority: "IC",
      email: "salma.rahimi@tii.ae",
      company_id: "tii",
      company_name: "Technology Innovation Institute",
      industry: "AI Research",
      status: "Bounced",
      tags: ["Engineering"],
      added_at: iso(12 * DAY),
      last_activity_at: iso(11 * DAY),
      last_activity: "Bounced — invalid address",
    },
    {
      id: "c12",
      first_name: "Tariq",
      last_name: "Nabil",
      title: "Director of Infrastructure",
      seniority: "Director",
      email: "tariq.nabil@khazna.com",
      company_id: "khazna",
      company_name: "Khazna Data Centers",
      industry: "Data Centers",
      status: "Not Contacted",
      tags: ["Infrastructure"],
      added_at: iso(1 * DAY),
    },
  ];
}
